version: 2
python:
  install:
    - method: pip
      path: .
conda:
  environment: environment.yaml
build:
  os: ubuntu-lts-latest
  tools:
    python: mambaforge-latest
sphinx:
  configuration: docs/source/conf.py